version: "3.8"
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: express_crud
      POSTGRES_USER: facugg
      POSTGRES_PASSWORD: root123
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
